name: secret_diary

dependencies:

  - pip:

    # .7z
    - py7zr
    # cli
    - click
    # text-formatting
    - rich
    - texttable
    - wcwidth
    - cjkwrap

    # git-hook
    - pre-commit

    # linting
    - pylint
    - isort
    - black
